---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - autoscaling.alibabacloud.com
  resources:
  - cronhorizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qa.shouqianba.com
  resources:
  - sqbapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qa.shouqianba.com
  resources:
  - sqbapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - qa.shouqianba.com
  resources:
  - sqbdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qa.shouqianba.com
  resources:
  - sqbdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - qa.shouqianba.com
  resources:
  - sqbplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qa.shouqianba.com
  resources:
  - sqbplanes/status
  verbs:
  - get
  - patch
  - update
